//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.3603
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NClass.AssemblyImport.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NClass.AssemblyImport.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die class ähnelt.
        /// </summary>
        internal static string Element_Class {
            get {
                return ResourceManager.GetString("Element_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die constructor ähnelt.
        /// </summary>
        internal static string Element_Constructor {
            get {
                return ResourceManager.GetString("Element_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delegate ähnelt.
        /// </summary>
        internal static string Element_Delegate {
            get {
                return ResourceManager.GetString("Element_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die elements ähnelt.
        /// </summary>
        internal static string Element_Elements {
            get {
                return ResourceManager.GetString("Element_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enum ähnelt.
        /// </summary>
        internal static string Element_Enum {
            get {
                return ResourceManager.GetString("Element_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die event ähnelt.
        /// </summary>
        internal static string Element_Event {
            get {
                return ResourceManager.GetString("Element_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die field ähnelt.
        /// </summary>
        internal static string Element_Field {
            get {
                return ResourceManager.GetString("Element_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die interface ähnelt.
        /// </summary>
        internal static string Element_Interface {
            get {
                return ResourceManager.GetString("Element_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die method ähnelt.
        /// </summary>
        internal static string Element_Method {
            get {
                return ResourceManager.GetString("Element_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die property ähnelt.
        /// </summary>
        internal static string Element_Property {
            get {
                return ResourceManager.GetString("Element_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die struct ähnelt.
        /// </summary>
        internal static string Element_Struct {
            get {
                return ResourceManager.GetString("Element_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load assembly since it seems to be not an assembly... ähnelt.
        /// </summary>
        internal static string Error_BadImageFormat {
            get {
                return ResourceManager.GetString("Error_BadImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error_MessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not open assembly due to missing referenced assemblies. ähnelt.
        /// </summary>
        internal static string Error_MissingReferencedAssemblies {
            get {
                return ResourceManager.GetString("Error_MissingReferencedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No assembly file to import. ähnelt.
        /// </summary>
        internal static string Error_NoAssembly {
            get {
                return ResourceManager.GetString("Error_NoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Import an assembly... ähnelt.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .NET assembly importer by Malte Ried ähnelt.
        /// </summary>
        internal static string Menu_ToolTip {
            get {
                return ResourceManager.GetString("Menu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all ähnelt.
        /// </summary>
        internal static string Modifier_All {
            get {
                return ResourceManager.GetString("Modifier_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die instance ähnelt.
        /// </summary>
        internal static string Modifier_Instance {
            get {
                return ResourceManager.GetString("Modifier_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die internal ähnelt.
        /// </summary>
        internal static string Modifier_Internal {
            get {
                return ResourceManager.GetString("Modifier_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die private ähnelt.
        /// </summary>
        internal static string Modifier_Private {
            get {
                return ResourceManager.GetString("Modifier_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die protected ähnelt.
        /// </summary>
        internal static string Modifier_Protected {
            get {
                return ResourceManager.GetString("Modifier_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die protected internal ähnelt.
        /// </summary>
        internal static string Modifier_ProtectedInternal {
            get {
                return ResourceManager.GetString("Modifier_ProtectedInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die public ähnelt.
        /// </summary>
        internal static string Modifier_Public {
            get {
                return ResourceManager.GetString("Modifier_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die static ähnelt.
        /// </summary>
        internal static string Modifier_Static {
            get {
                return ResourceManager.GetString("Modifier_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Settings_CancelButton {
            get {
                return ResourceManager.GetString("Settings_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Aggregations ähnelt.
        /// </summary>
        internal static string Settings_CreateAggregations {
            get {
                return ResourceManager.GetString("Settings_CreateAggregations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a label on the side of the aggregation ähnelt.
        /// </summary>
        internal static string Settings_CreateLabel {
            get {
                return ResourceManager.GetString("Settings_CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;&lt;&apos; is not allowed ähnelt.
        /// </summary>
        internal static string Settings_Error_AngleBracketNotAllowed {
            get {
                return ResourceManager.GetString("Settings_Error_AngleBracketNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name ähnelt.
        /// </summary>
        internal static string Settings_Error_NoTemplateName {
            get {
                return ResourceManager.GetString("Settings_Error_NoTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a template first ähnelt.
        /// </summary>
        internal static string Settings_Error_NoTemplateSelected {
            get {
                return ResourceManager.GetString("Settings_Error_NoTemplateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This template can&apos;t be deleted ähnelt.
        /// </summary>
        internal static string Settings_Error_TemplateCantBeDeleted {
            get {
                return ResourceManager.GetString("Settings_Error_TemplateCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import everything except ähnelt.
        /// </summary>
        internal static string Settings_ImportExcept {
            get {
                return ResourceManager.GetString("Settings_ImportExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Element ähnelt.
        /// </summary>
        internal static string Settings_ImportExcept_Element {
            get {
                return ResourceManager.GetString("Settings_ImportExcept_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modifier ähnelt.
        /// </summary>
        internal static string Settings_ImportExcept_Modifier {
            get {
                return ResourceManager.GetString("Settings_ImportExcept_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string Settings_OKButton {
            get {
                return ResourceManager.GetString("Settings_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove fields which constructs the aggregation (code generation won&apos;t produce any code for that aggregation) ähnelt.
        /// </summary>
        internal static string Settings_RemoveFields {
            get {
                return ResourceManager.GetString("Settings_RemoveFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template ähnelt.
        /// </summary>
        internal static string Settings_Template {
            get {
                return ResourceManager.GetString("Settings_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Settings_Template_DeleteButton {
            get {
                return ResourceManager.GetString("Settings_Template_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;last used&gt; ähnelt.
        /// </summary>
        internal static string Settings_Template_LastUsed {
            get {
                return ResourceManager.GetString("Settings_Template_LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        internal static string Settings_Template_LoadButton {
            get {
                return ResourceManager.GetString("Settings_Template_LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Store ähnelt.
        /// </summary>
        internal static string Settings_Template_StoreButton {
            get {
                return ResourceManager.GetString("Settings_Template_StoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import settings ähnelt.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
